version: '3'

services:

  backend:
    container_name: backend
    build: ./backend
    env_file: ./be.env
    restart: always
    ports:
      - 3000:3000

  frontend:
    container_name: frontend
    build: ./frontend
    env_file: ./fe.env
    restart: always
    ports:
      - 2345:2345
